# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dan Drust
logo: https://render.bitstrips.com/v2/cpanel/74199580-3d4e-4477-8454-45c0e64aaa76-7bae3348-5189-4dda-8128-de7baa798685-v1.png?transparent=1&palette=1&width=175
email: dandrust@gmail.com
description: Ruby on Rails Developer
location: Grand Rapids, MI
baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://dandrust.github.io' # the base hostname & protocol for your site, e.g. http://example.com
github_username: dandrust
author: Dan Drust
header_links:
  - About
  - Code
  - Thoughts

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
